php artisan make:model TaiKhoan
php artisan make:model BaiViet
php artisan make:model LoaiMyPham
php artisan make:model MyPham
php artisan make:model GiaBan
php artisan make:model NhanVien
php artisan make:model KhachHang
php artisan make:model NhaCC
php artisan make:model HoaDonNhap
php artisan make:model ChiTietHoaDonNhap
php artisan make:model HoaDonBan
php artisan make:model ChiTietHoaDonBan